# Generated by Django 4.0.3 on 2022-07-08 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_rename_popular_venue_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.TextField()),
                ('payment_status', models.BooleanField(blank=True, default=False, help_text='Designates whether the payment is successfull.', verbose_name='Is Paid')),
                ('bottle_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('cover_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_tickets', models.IntegerField(blank=True, default=1, null=True)),
                ('processing_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('pulse_service_charges', models.IntegerField(blank=True, default=0, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_transaction', to='events.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
