# Generated by Django 4.0.3 on 2022-08-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_eventtransaction_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtransaction',
            name='service_tip',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
