# Generated by Django 4.0.3 on 2022-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coverPhoto',
            field=models.ImageField(blank=True, upload_to='event_cover'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='event'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_picture',
            field=models.ImageField(blank=True, upload_to='university'),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='venue'),
        ),
    ]
