# Generated by Django 4.0.3 on 2022-03-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_created_by_alter_university_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
