# Generated by Django 4.0.3 on 2022-06-26 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_venue_friday_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestvenue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestvenue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
