# Generated by Django 4.0.3 on 2022-04-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_university_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='university_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_campus', to='events.university'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_venue_name', to='events.venue'),
        ),
    ]
