# Generated by Django 4.0.3 on 2022-06-26 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_requestvenue_created_at_requestvenue_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='friday_end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='friday_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='monday_end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='monday_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='saturday_end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='saturday_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='sunday_end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='sunday_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thursday_end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thursday_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tuesday_end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tuesday_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='wednesday_end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='wednesday_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, help_text='Enter Time', null=True),
        ),
    ]
