# Generated by Django 4.0.3 on 2022-04-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_university_campus_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_picture',
            field=models.ImageField(blank=True, upload_to='university/%Y/%m/%d/'),
        ),
    ]
