# Generated by Django 4.0.3 on 2022-06-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_venue_friday_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='Popular',
            field=models.BooleanField(blank=True, default=False, help_text='Designates whether the venue is popular or not.', verbose_name='popular'),
        ),
        migrations.AddField(
            model_name='venue',
            name='premium',
            field=models.BooleanField(blank=True, default=False, help_text='Designates whether the venue is premium or not.', verbose_name='Premium'),
        ),
    ]
