# Generated by Django 4.0.3 on 2022-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_university_university_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coverPhoto',
            field=models.ImageField(blank=True, upload_to='event_cover/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='event/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='venue/%Y/%m/%d/'),
        ),
    ]
