# Generated by Django 4.0.3 on 2022-07-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_venue_popular_venue_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='Popular',
            new_name='popular',
        ),
    ]
