# Generated by Django 4.0.3 on 2022-07-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_start_reminder_sent',
            field=models.BooleanField(blank=True, default=False, help_text='Designates whether the event start reminder sent to host.', verbose_name='Event start reminder sent'),
        ),
    ]
