# Generated by Django 4.0.3 on 2022-05-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
