# Generated by Django 4.0.3 on 2022-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_venue_address_venue_description_venue_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
