# Generated by Django 4.0.3 on 2022-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_venue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='liked',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
