# Generated by Django 4.0.3 on 2022-05-30 17:01

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventstatus_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
    ]
