# Generated by Django 4.0.3 on 2022-05-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_menuimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
