# Generated by Django 4.0.3 on 2022-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_venue_email_venue_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='status',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
