# Generated by Django 4.0.3 on 2022-06-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_status_university_status_venue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='going',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='joined',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
