# Generated by Django 4.0.3 on 2022-06-06 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0019_eventstatus_going_eventstatus_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_requested_venue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requested Venues',
            },
        ),
    ]
