# Generated by Django 4.0.3 on 2022-06-07 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0020_requestvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='promoter_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoter_user_venue', to=settings.AUTH_USER_MODEL),
        ),
    ]
