# Generated by Django 4.0.3 on 2022-06-07 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0021_venue_promoter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked', models.BooleanField(blank=True, default=0, null=True)),
                ('joined', models.BooleanField(blank=True, default=0, null=True)),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_venue_interaction', to=settings.AUTH_USER_MODEL)),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_status', to='events.venue')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
