# Generated by Django 4.0.3 on 2022-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_venuestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
