Data = {
"user_created":"User created successfully.",
"user_updated":"User information updated successfully.",
"user_deleted":"User deleted successfully.",
"validation_error":"Event creation error. Please try again.",
"update_data_id_required":"ID missing.",
"user_not_exists":"User not found.",
"user_exists":"User found.",
"device_created":"Device created successfully.",
"device_not_exists":"Devices not found.",
"device_exists":"Devices found.",
"otp_required":"OTP is required.",
"otp_sent":"OTP sent successfully!",
"twilio_unable_to_send":"Unable to send OTP. Please try again.",
"invalid_phone_number":"Invalid phone number.",
"too_many_tries":"Action attempted too many times. Please try again in an hour.",
"invalid_otp":"Invalid OTP. Try again.",
"otp_verified":"OTP verified successfully!",
"card_billing_created":"Card billing saved successfully!",
"user_phone_not_found":"User phone not found.",
"card_exists":"Card billing list found.",
"card_not_exists":"Card not found. Try another.",
"Create_event_user_id_required":"User ID missing. Please try again.",
"event_created":"Event created successfully!",
"event_updated":"Event updated successfully!",
"event_archived":"Event archived successfully!",
"event_not_exists":"Event not found.",
"event_image_deleted":"Event Image deleted successfully!",
"event_image_not_exists":"Event does not have any media.",
"event_open_guest_list_full":"Guest list is full. Please try again later.",
"event_status_created":"Event status created successfully!",
"event_status_updated":"Event status updated successfully!",
"event_left":"You have left this event.",
"event_status_not_exists":"Event status not found.",
"invalid_event_status":"Invalid status provided.",
"event_share_required_data":"Data missing.",
"event_share_to_user_not_exists":"User not found.",
"event_shared":"Event sent!",
"event_share_required_to_user_id":"User not found.",
"venue_status_created":"Venue status created successfully!",
"venue_status_updated":"Venue status updated successfully!",
"notification_not_exists":"Notification not found",
"notification_event_accepted":"Event invite accepted!",
"invalid_notification_status":"Please Accept or Decline event invite.",
"universities_found":"University found.",
"universities_not_found":"University not found.",
"venue_created":"Venue created successfully!",
"venue_requested":"Venue requested successfully! Thank you for improving Pulse!",
"venue_found":"Venue found",
"venue_found_with_no_events":"Venue has no events",
"venue_not_found":"Venue not found :(",
"notificaion_created":"Notification created successfully!",
"notificaion_deleted":"Notification deleted successfully!",
"notificaion_not_found":"Notification not found!",
"faq_found":"FAQ's found",
"faq_not_found":"FAQ's not found",
"notificaion_mark_read":"Notification marked as read.",
"friend_request_created":"Friend request sent!",
"friend_request_already_sent":"Friend request already sent!.",
"invite_for_app_install_sms_sent":"Text message sent to phone numbers!",
"invite_for_app_install_sms_content":"You have been invited to an event on Pulse App hosted by #user_name#. Clicking the link to download the app and RVSP your invite!: https://google.com",
"friend_requests_not_found":"Friend request not found.",
"friend_requests_found":"Friend request found.",
"friend_request_already_accepted":"Friend request already accepted.",
"friend_request_accepted":"Friend request accepted!",
"friend_request_declined":"Friend request declined!",
"already_unfriend":"Error. You two are currently not friends.",
"friend_request_un_friend":"Friend request removed.",
"invalid_friend_request_status":"Please respond to friend request.",
"event_payment_intent_required_param":"Error with payments. Please try again.",
"event_payment_intent_created":"Payment initiated successfully.",
"event_transaction_for_ticket_created":"Event transaction successful!",
}

