# Generated by Django 4.0.3 on 2022-05-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='notification',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_notification', to='general.notification'),
        ),
    ]
