# Generated by Django 4.0.3 on 2022-07-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('Users', 'Users'), ('Events', 'Events'), ('Venues', 'Venues'), ('Ticket', 'Ticket')], default='Users', max_length=100, null=True, verbose_name='Report Type')),
                ('report_type_id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('report_reason', models.CharField(choices=[('Unprofessional', 'Unprofessional / bad service'), ('Fake', 'Fake / impersonation'), ('Scam', 'Scam or fraud'), ('Spam', 'Spam'), ('False_Information', 'False Information'), ('Nudity', 'Nudity or sexual activity'), ('Underage_Drinking', 'Underage drinking'), ('Violence', 'Violence, drugs or dangerous organization'), ('Hate', 'Hate or terrorist groups'), ('Dangerous_Organization', 'Violence, drugs or dangerous organization'), ('Bullying', 'Bullying or harassment'), ('Illegal', 'Illegal/ criminal activities'), ('Suicide', 'Suicide or self-injury')], default='Fake', max_length=100, null=True, verbose_name='Report Type')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
