# Generated by Django 4.0.3 on 2022-07-23 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_by_user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.CharField(choices=[('Unprofessional', 'Unprofessional / bad service'), ('Fake', 'Fake / impersonation'), ('Scam', 'Scam or fraud'), ('Spam', 'Spam'), ('False_Information', 'False Information'), ('Nudity', 'Nudity or sexual activity'), ('Underage_Drinking', 'Underage drinking'), ('Violence', 'Violence, drugs or dangerous organization'), ('Hate', 'Hate or terrorist groups'), ('Dangerous_Organization', 'Violence, drugs or dangerous organization'), ('Bullying', 'Bullying or harassment'), ('Illegal', 'Illegal/ criminal activities'), ('Suicide', 'Suicide or self-injury')], default='Fake', max_length=100, null=True, verbose_name='Report Reason'),
        ),
    ]
