# Generated by Django 4.0.3 on 2022-07-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_report_reported_by_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_reason',
            field=models.CharField(choices=[('Unprofessional', 'Unprofessional / bad service'), ('Fake', 'Fake / impersonation'), ('Scam', 'Scam or fraud'), ('Spam', 'Spam'), ('False_Information', 'False Information'), ('Nudity', 'Nudity or sexual activity'), ('Underage_Drinking', 'Underage drinking'), ('Violence', 'Violence, drugs or dangerous organization'), ('Hate', 'Hate or terrorist groups'), ('Dangerous_Organization', 'Violence, drugs or dangerous organization'), ('Bullying', 'Bullying or harassment'), ('Illegal', 'Illegal/ criminal activities'), ('Suicide', 'Suicide or self-injury')], default='Fake', max_length=100, verbose_name='Report Reason'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Users', 'Users'), ('Events', 'Events'), ('Venues', 'Venues'), ('Ticket', 'Ticket')], default='Users', max_length=100, verbose_name='Report Type'),
        ),
    ]
