# Generated by Django 4.0.3 on 2022-06-24 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('month', django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True))),
                ('year', django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True))),
                ('cvv', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('card_holder_name', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('country', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'))),
                ('address', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'))),
                ('city', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='City'))),
                ('state', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='State'))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
