# Generated by Django 4.0.3 on 2022-04-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_university_campus_alter_event_venue'),
        ('authentication', '0003_user_uid_user_university_user_user_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='events.university'),
        ),
    ]
