# Generated by Django 4.0.3 on 2022-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Device Id'),
        ),
    ]
