# Generated by Django 4.0.3 on 2022-04-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_profile_picture_image_alter_user_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.IntegerField()),
                ('otp', models.IntegerField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
