# Generated by Django 4.0.3 on 2022-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_smsotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Degree Title'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_access_type',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=10, null=True),
        ),
    ]
