# Generated by Django 4.0.3 on 2022-06-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_date_of_birth_user_degree_title_user_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('PROMOTER', 'PROMOTER'), ('VENUE_OWNER', 'VENUE_OWNER'), ('PULSE_ADMIN', 'PULSE_ADMIN')], default='REGULAR', max_length=50, null=True),
        ),
    ]
