name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

        # Install Python Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAT2NK673BNLTM6Z5B"
          aws-secret-access-key: "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"
          aws-region: us-east-1
      - name: Run migrations
        run: python manage.py migrate
        # Build App and Run Application Test
      # - name: Build Application and Run unit Test
      #   run: python run.py & pytest

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAT2NK673BNLTM6Z5B"
          aws-secret-access-key: "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"
          aws-region: us-east-1

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          # Assuming the Deployment Group is already setup
          aws deploy create-deployment \
            --application-name pulse-api \
            --deployment-group-name pulseAppDeploy \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}